---

title: Metamem.cf (clock federation)
timezone: UTC
description: Произведения цифрового искусства
room-projector: 160000
hall-projector: 320000
street-projector: 500000
room-player: 11250
hall-player: 11250
street-player: 11250
room-screen: 0
hall-screen: 35000
street-screen: 0


show_sidebar: false
show_downloads: false
show_title: false
show_description: false
git_branch: master

theme: jekyll-theme-minimal

include: ['.htaccess']

exclude:
  template.md
  template.html

use_github_wiki: false
use_prose_io: true
custom_head: false
custom_sidebar: false
custom_footer: false

prose:
  rooturl: 'https://metamem.cf'
  siteurl: 'https://metamem.cf'
  relativeLinks: 'https://prose.github.io/starter/links.jsonp'
  media: '/images'

  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /assets
    - 404.md
    - README.md
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
